version: "3.1"

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb_tasks
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - "27017:27017"
